### local
GET http://localhost:3000/health HTTP/1.1

### container
GET http://localhost:49160/health HTTP/1.1

### through front door
GET https://fd-endpoint-aca-dev-001-chbmgzgtgzgscveb.z01.azurefd.net/health HTTP/1.1
