name: Deploy Infrastructure

on: [push]

env:
  BASE_NAME: aca-dev-001
  LOCATION: uksouth

jobs:
  deploy-ca-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: Set variables
        id: set-vars
        run: | 
          echo "RESOURCE_GROUP_NAME=rg-${{ env.BASE_NAME }}" >> $GITHUB_OUTPUT
          echo "DEPLOYMENT_NAME=${{ env.BASE_NAME }}-deployment-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Create Resource Group
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az group create --name ${{ steps.set-vars.outputs.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}   

      - name: Deploy Bicep
        uses: Azure/cli@v1
        with:
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/src/arm/deploy.sh 
            $GITHUB_WORKSPACE/src/arm/deploy.sh ${{ steps.set-vars.outputs.RESOURCE_GROUP_NAME }} ${{ steps.set-vars.outputs.DEPLOYMENT_NAME }} ${{ env.BASE_NAME }} $GITHUB_WORKSPACE/src/arm/

      - name: Get Outputs
        id: get-outputs
        run: |
          # echo "PRIVATE_LINK_ENDPOINT_CONNECTION_ID=$(jq -r '.privateLinkEndpointConnectionId' $GITHUB_WORKSPACE/src/arm/outputs.json)" >> $GITHUB_OUTPUT
          echo "FQDN=$(jq -r '.fqdn' $GITHUB_WORKSPACE/src/arm/outputs.json)" >> $GITHUB_OUTPUT

      # - name: Approve Private Endpoint Connection
      #   uses: Azure/cli@v1
      #   with:
      #     inlineScript: |
      #       az network private-endpoint-connection approve --id ${{ steps.get-outputs.outputs.PRIVATE_LINK_ENDPOINT_CONNECTION_ID }} --description "(Frontdoor) Approved by CI/CD"

      - name: Final Outputs
        run: |
          echo "...Deployment FINISHED!"
          echo "Please wait a few minutes until endpoint is established..."
          echo "--- FrontDoor FQDN: https://${{ steps.get-outputs.outputs.FQDN }} ---"            
