name: Deploy Infrastructure

on: [push]

env:
  BASE_NAME: aca-dev-001
  LOCATION: uksouth

jobs:
  deploy-ca-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register Providers
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az provider register --wait --namespace Microsoft.App
            az provider register --wait --namespace Microsoft.ContainerService
            az provider register --wait --namespace Microsoft.Cdn          
