name: Deploy Infrastructure

on: [push]

env:
  BASE_NAME: aca-dev-001
  LOCATION: uksouth

jobs:
  deploy-ca-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: Set variables
        id: set-vars
        run: | 
          echo "RESOURCE_GROUP_NAME=rg-${{ env.BASE_NAME }}" >> $GITHUB_OUTPUT
          echo "DEPLOYMENT_NAME=${{ env.BASE_NAME }}-deployment-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Register Providers
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az provider register --wait --namespace Microsoft.App
            az provider register --wait --namespace Microsoft.ContainerService
            az provider register --wait --namespace Microsoft.Cdn   

      - name: Create Resource Group
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az group create --name ${{ steps.set-vars.outputs.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}   

      - name: Deploy Bicep
        uses: Azure/cli@v1
        with:
          azcliversion: 2.45.0
          inlineScript: |
            az deployment group create -f ./src/arm/main.bicep -g rg-aca-dev-001 --parameters baseName=aca-dev-001
